name: Deploy Prod Workflow
on: workflow_dispatch

jobs:
    deployprod:
        runs-on: ubuntu-latest
        steps:
          - name: init
            uses: | 
                actions/checkout@v4
                pnpm/action-setup@v3
          - name: deploy
            run: pnpm dlx @azure/static-web-apps-cli deploy ./dist --app-name stapp-vue2048-prod --env=production